name: Fernando Crespo


permalink: /:year/:month/:day/:title/

timezone: America/Sao_Paulo
default_locale: pt-BR

markdown: kramdown
markdown_ext: markdown,mkd,mkdn,md,txt

excerpt_separator: <!--more-->


gems:
  - jekyll-gist
theme: jekyll-theme-architect