title: Fernando Crespo
author: Fernando Crespo
email: fernando82@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about my stuff

services:
  - name: github
    url: https://github.com/fcrespo82
  - name: bitbucket
    url: https://bitbucket.com/fcrespo82
  - name: twitter
    url: https://twitter.com/fcrespo82
  - name: mail
    url: mailto:fernando82@gmail.com

permalink: /:year/:month/:day/:title/

timezone: America/Sao_Paulo
default_locale: pt-BR

markdown: kramdown
markdown_ext: markdown,mkd,mkdn,md,txt

excerpt_separator: <!--more-->

plugins:
  - jekyll-gist
